function plotCute1(xLabel,yLabel,ax,plotTitle,plotLegend,showLegend,varargin)
%% PLOTCUTE1 takes 'x' and 'y' labels as input along with the axis, and 
% improves the plot with fixed settings        

if nargin == 7
    legOrient = varargin{1};
else
    legOrient = 'Vertical'; % Default legend orientation
end

hXLabel = xlabel(ax,xLabel,'FontSize',10);
hYLabel = ylabel(ax,yLabel,'FontSize',10); 
hTitle = title(ax,plotTitle);

if showLegend
    hLegend = legend(plotLegend);
    set(hLegend,...
        'FontName'   , 'Helvetica',...
        'FontSize'   , 10         ,...
        'Orientation', legOrient  ); % 6 for publication
end

set(gca                       , ...
    'FontName'   , 'Helvetica', ...
    'FontSize'   , 10          ); % 8 for publication
set([hXLabel, hYLabel,hTitle], ...
    'FontName'   , 'Helvetica',...
    'FontSize'   , 10         ); % 8 for publication
set(ax, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         ); %'YTick'       , -0.008:0.002:0.008, ...

ax.XGrid = 'off';

end